config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'norte', to: 'estados#norte'
  get 'norte/acre', to: 'estados#show'

  get  'ritmos', to: 'pages#ritmos'
  get 'ritmos/:id', to: 'pages#show', as: :ritmo
  resources :estados, except: [:edit, :update] do
    resources :pontes, only: [:new, :create]

  end
  resources :pontes, only: :destroy


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estado.rb
class Estado < ApplicationRecord
  has_many :pontes, dependent: :destroy
  has_many :ritmos, through: :pontes


  validates :nome, presence: true
end

app/models/ponte.rb
class Ponte < ApplicationRecord
  belongs_to :ritmo
  belongs_to :estado

  validates :comment, length: { minimum: 6 }
  validates :ritmo_id, uniqueness: { scope: :estado_id, message: "is already in the list" }
end

app/models/ritmo.rb
class Ritmo < ApplicationRecord
  has_many :pontes

  validates :nome, presence: true
  validates :descricao, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  def norte
    @estados_norte = Estado.where(regiao:"Norte")
  end

  def show
    @acre = Ritmo.where(nome:"Acre")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def ritmos
    @ritmos = Ritmo.all
  end

  def show
    @ritmo = Ritmo.find(params[:id])
  end
end

app/controllers/pontes_controller.rb
class PontesController < ApplicationController
  before_action :set_ponte, only: :destroy
  before_action :set_estado, only: [:new, :create]

  def new
    @ponte = Ponte.new
  end

  def create
    @ponte = Ponte.new(ponte_params)
    @ponte.estado = @estado
    if @ponte.save

      redirect_to estado_path(@estado.id,@ponte.ritmo)
    else
      render :new
    end
  end

  def destroy
    @ponte.destroy
    redirect_to estado_path(@ponte.ritmo)
  end

  private

  def ponte_params
    params.require(:ponte).permit(:comment, :ritmo_id)
  end

  def set_ponte
    @ponte = Ponte.find(params[:id])
  end

  def set_estado
    @estado = Estado.find(params[:estado_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pontes_helper.rb
module PontesHelper
end

app/views/estados/index.html.erb
<div class="texto">
  <h1>Região</h1>
  <p><%= link_to'Norte'%></p>
  <p>Nordeste</p>
  <p>Centro</p>
  <p>Oeste</p>
  <p>Sudeste</p>
  <p>Sul</p>
</div>
<div class="texto">
  <h1>Estados</h1>
  <p>Acre Amazonas Amapá Pará Rondônia Roraima Tocantins</p>
</div>

app/views/estados/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Criar Novo Estado</h3>
        <%= simple_form_for @estado do |f| %>
          <%= f.input :nome, placeholder: 'Estado' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/estados/norte.html.erb
<div class="texto">
  <h1>Região</h1>
  <p id="te>Norte</p>
  <p>Nordeste</p>
  <p>Centro</p>
  <p>Oeste</p>
  <p>Sudeste</p>
  <p>Sul</p>
</div>
<div class="texto">
  <h1>Estados</h1>
</div>

<div class="main-container">
  <% @estados_norte.each do |rit| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/photos/empty-3d-geographic-map-abstract-levels-render-picture-id1328792990)">
      <div>
          <%= link_to rit.nome, norte_acre_path %>
      </div>
    </div>
  <% end %>
</div>

app/views/estados/show.html.erb
<div class="texto">
  <h1>Região</h1>
  <p><%= link_to'Norte'%></p>
  <p>Nordeste</p>
  <p>Centro</p>
  <p>Oeste</p>
  <p>Sudeste</p>
  <p>Sul</p>
</div>
<div class="texto">
  <h1>Acre</h1>
</div>
<% @acre.each do |rit| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/photos/portrait-of-a-smiling-beautiful-boy-listening-music-with-headphones-picture-id1356532153)">
    <div>
        <%= rit.nome %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Learn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Academy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Podcast</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Soundtracks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">AboutUs</a>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRitudb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="texto">
  <h1>Região</h1>
  <button id="teste"><%= link_to 'Norte', norte_path %></button>
  <button id="teste">Nordeste</button>
  <button id="teste">Centro</button>
  <button id="teste">Oeste</button>
  <button id="teste">Sudeste</button>
  <button id="teste">Sul</button>
</div>
<div class="texto">
  <h1>Estados</h1>
  <p>Acre Amazonas Amapá Pará Rondônia Roraima Tocantins</p>
</div>
    <%= render "pages/mapa" %>

app/views/pages/ritmos.html.erb
<div>
  <h1>Região Norte Nordeste Centro Oeste Sudeste Sul</h1>
</div>
<div>
  <h1>Estados Acre Amazonas Amapá Pará Rondônia Roraima Tocantins</h1>
</div>

<% @ritmos.each do |rit| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <div>
        <%= rit.nome %>
    </div>
  </div>
<% end %>

app/views/pages/show.html.erb
<%= @ritmo.nome %>
<h1>Região</h1>
<p>Estado</p>

<%= image_tag "mapa_norte.png", alt: "Mapa", width: 200 %>

<h1>"Rocha!Égua!"</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi libero expedita voluptatibus nisi facere dolore eveniet distinctio fuga! Molestias illo a sunt facilis voluptates labore repellat numquam esse corrupti tempore.</p>

<button>Material de estudo</button>

app/views/pontes/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Ritmos de <%= @estado.nome %> </h3>
        <%= link_to "Ver", estado_path(@estado[:id]), class: "btn btn-ghost" %>
      <div class="bg-white rounded p-3 shadow">
        <h3>Adicionar ritmo para <%= @estado.nome %> </h3>
        <%= simple_form_for [@estado, @ponte] do |f| %>
          <%= f.association :ritmo, label_method: :nome, value_method: :id, include_blank: false, input_html: { data: { controller: 'select2' }} %>
          <%= f.input :comment, placeholder: '
          Descrever o ritmo' %>
          <%= f.submit class: "btn btn-ghost" %>
        <% end %>
      </div>
      <%= link_to "Voltar", root_path, class: "btn btn-ghost" %>
    </div>
  </div>
</div>